services:
  app:
    container_name: url-shortener
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      - CONFIG_PATH=/app/config/docker.yaml
    volumes:
      - ./config:/app/config
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "url"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: